### ISSUE TITLE
Argument starting with an underscore

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#34]
Currently, keyword arguments starting with an underscore break defopt.  With
```
@defopt.run
def main(_x: str = "foo"):
    pass
```
we get
```
$ python /tmp/foo.py -h
usage: foo.py [-h] [-_ X]

optional arguments:
  -h, --help    show this help message and exit
  -_ X, ---x X

$ python /tmp/foo.py -_ 1
Traceback (most recent call last):
  File "/tmp/foo.py", line 4, in <module>
    def main(_x: str = "foo"):
  File "/usr/lib/python3.6/site-packages/defopt.py", line 101, in run
    return _call_function(args._func, args)
  File "/usr/lib/python3.6/site-packages/defopt.py", line 319, in _call_function
    arg = getattr(args, name)
AttributeError: 'Namespace' object has no attribute '_x'

$ python /tmp/foo.py ---x 1
Traceback (most recent call last):
  File "/tmp/foo.py", line 4, in <module>
    def main(_x: str = "foo"):
  File "/usr/lib/python3.6/site-packages/defopt.py", line 101, in run
    return _call_function(args._func, args)
  File "/usr/lib/python3.6/site-packages/defopt.py", line 319, in _call_function
    arg = getattr(args, name)
AttributeError: 'Namespace' object has no attribute '_x'
```
(and similarly when there are multiple such arguments).

I think it makes sense to treat such arguments as private and not expose them to the CLI.

**Comment by evanunderscore** [comment]
Sounds good to me. Would you like to work on a patch?

**Comment by anntzer** [comment]
Probably not right now...
