### ISSUE TITLE
keyword-only arguments can't start with the letter h

### ISSUE THREAD

**Issue by johnfarina** [evanunderscore/defopt#62]
As it conflicts with the autogenerated `-h/--help` option. Here's a contrived minimal example, and the resulting traceback

```python
import defopt
def foo(*, hello: str = "Hi!"):
    print(hello)
defopt.run(foo, argv=['-h'])
```
```python
Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    defopt.run(foo, argv=['-h'])
  File "/usr/local/lib/python3.7/site-packages/defopt.py", line 94, in run
    parser = _create_parser(funcs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/defopt.py", line 116, in _create_parser
    _populate_parser(funcs, parser, parsers, short, strict_kwonly)
  File "/usr/local/lib/python3.7/site-packages/defopt.py", line 257, in _populate_parser
    _add_argument(parser, name, short, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/defopt.py", line 268, in _add_argument
    return parser.add_argument(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1367, in add_argument
    return self._add_action(action)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1730, in _add_action
    self._optionals._add_action(action)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1571, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1381, in _add_action
    self._check_conflict(action)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1520, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1529, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -h/--hello: conflicting option string: -h
```

A temporary workaround is to disable the automatic creation of the corresponding short argument:  `defopt.run(foo, short={"hello": "hello"}, argv=['-h'])` but that's kludgy.

**Comment by anntzer** [comment]
Now that https://github.com/evanunderscore/defopt/pull/60 has been merged, I think the correct fix is something like
```
diff --git i/defopt.py w/defopt.py
index 51f66af..000237f 100644
--- i/defopt.py
+++ w/defopt.py
@@ -189,6 +189,8 @@ def _populate_parser(func, parser, parsers, short, strict_kwonly):
     if short is None:
         count_initials = Counter(name[0] for name in sig.parameters
                                  if name not in positionals)
+        if parser.add_help:
+            count_initials['h'] += 1
         short = dict(
             (name.replace('_', '-'), name[0]) for name in sig.parameters
             if name not in positionals and count_initials[name[0]] == 1)
```

**Comment by kyleabeauchamp** [comment]
Looks like this issue is fixed in master but not yet released.

**Comment by evanunderscore** [comment]
Thanks for the reminder, I'll publish a new release by the end of the week.

**Comment by evanunderscore** [comment]
5.1.0 should be up now, let me know if you have any issues.
